#!/usr/bin/env bash

# Functions path
FUNCTIONS_PATH="$DOTFILES_DIR/bash/functions"

# source all the functions
# Depended up functions
source "$FUNCTIONS_PATH/dep/bash-login.sh";

# User functions
source "$FUNCTIONS_PATH/tools/create-project.sh";
source "$FUNCTIONS_PATH/tools/gs.sh";
source "$FUNCTIONS_PATH/tools/mkcd.sh";
