#!/usr/bin/env bash

# ANSI Colors
# The \033 is the octal code for escape
# This uses the British English Spelling. Fight me.

# REGULAR
export COLOUR_BLACK='\033[0;30m';
export COLOUR_BLUE='\033[0;34m';
export COLOUR_CYAN='\033[0;36m'
export COLOUR_GREEN='\033[0;32m';
export COLOUR_PURPLE='\033[0;35m';
export COLOUR_RED='\033[0;31m';
export COLOUR_WHITE='\033[0;37m';
export COLOUR_YELLOW='\033[0;33m';
# BOLD
export COLOUR_BOLD_BLACK='\033[1;30m';
export COLOUR_BOLD_BLUE='\033[1;34m';
export COLOUR_BOLD_CYAN='\033[1;36m';
export COLOUR_BOLD_GREEN='\033[1;32m';
export COLOUR_BOLD_PURPLE='\033[1;35m';
export COLOUR_BOLD_RED='\033[1;31m';
export COLOUR_BOLD_WHITE='\033[1;37m';
export COLOUR_BOLD_YELLOW='\033[1;33m';
# UNDERLINE
export COLOUR_UNDERLINE_BLACK='\033[4;30m';
export COLOUR_UNDERLINE_BLUE='\033[4;34m';
export COLOUR_UNDERLINE_CYAN='\033[4;36m';
export COLOUR_UNDERLINE_GREEN='\033[4;32m';
export COLOUR_UNDERLINE_PURPLE='\033[4;35m';
export COLOUR_UNDERLINE_RED='\033[4;31m';
export COLOUR_UNDERLINE_WHITE='\033[4;37m';
export COLOUR_UNDERLINE_YELLOW='\033[4;33m';
# BACKGROUND
export COLOUR_BACKGROUND_BLACK='\033[40m';
export COLOUR_BACKGROUND_BLUE='\033[44m';
export COLOUR_BACKGROUND_CYAN='\033[46m';
export COLOUR_BACKGROUND_GREEN='\033[42m';
export COLOUR_BACKGROUND_PURPLE='\033[45m';
export COLOUR_BACKGROUND_RED='\033[41m';
export COLOUR_BACKGROUND_WHITE='\033[47m';
export COLOUR_BACKGROUND_YELLOW='\033[43m';
# RESET
export COLOUR_RESET='\033[0m';
# END COLOURS

# Set variables that my tools will depend on
export PROJECT_DIR="${HOME}/Projects";
export DOTFILES_DIR="${HOME}/.dotfiles";
export SCHOOL_DIR="${HOME}/Documents/School/"

# System variables

# ~/bin is for scripts installed by these dotfiles
# ~/.bin is for scripts wrote by the user
# ~/.local/bin is for applications installed by the user
# ~/.deno/bin is for deno - https://deno.land/
PATH="$DOTFILES_DIR/bin:$HOME/bin:$HOME/.bin/$HOME/.local/bin:$HOME/.deno/bin:$PATH";

# History File Config
export HISTSIZE=5000;
export HISTFILESIZE=10000;
